name: Chitchat
main: com.demigodsrpg.chitchat.Chitchat
version: 1.0.0
description: The simplest plugin for chitchat.
authors: [HmmmQuestionMark]
commands:
  ccreload:
    usage: /ccreload
    aliases: [ccr]
  ccmute:
    usage: /ccmute <player>
    aliases: [ccm]
  ccunmute:
    usage: /ccunmute <player>
    aliases: [ccum]
permisions:
  chitchat.reload:
    default: op
  chitchat.mute:
    default: op
  chitchat.unmute:
    default: op