name: ${project.name}
main: com.demigodsrpg.chitchat.Chitchat
api-version: 1.21.8
version: ${project.version}
description: The simplest plugin for chitchat.
authors: [HQM]
commands:
  mutelist:
    usage: /mutelist
    aliases: [mutel]
  mute:
    usage: /mute <player> [time] [unit]
  unmute:
    usage: /unmute <player>
  message:
    usage: /message <player> <message>
    aliases: [dm, pm, whisper, tell]
  reply:
    usage: /reply <message>
    aliases: [r, rep]
permisions:
  chitchat.delete:
    default: op
  chitchat.mute:
    default: op
  chitchat.unmute:
    default: op
  chitchat.color:
    default: false
  chitchat.msg:
    default: true