name: ${project.name}
main: com.demigodsrpg.chitchat.Chitchat
version: ${project.version}
description: The simplest plugin for chitchat.
authors: [HmmmQuestionMark]
commands:
  ccreload:
    usage: /ccreload
  ccmutelist:
    usage: /ccmutelist
    aliases: [mutelist, ccml]
  ccmute:
    usage: /ccmute <player> [time] [unit]
    aliases: [mute, ccm]
  ccunmute:
    usage: /ccunmute <player>
    aliases: [unmute, ccum]
  ccmsg:
    usage: /ccmsg <player> <message>
    aliases: [msg, pm, whisper, tell]
  ccreply:
    usage: /ccreply <message>
    aliases: [ccr, rep, r]
permisions:
  chitchat.reload:
    default: op
  chitchat.mute:
    default: op
  chitchat.unmute:
    default: op
  chitchat.color:
    default: false
  chitchat.msg:
    default: true