name: ${project.name}
main: com.demigodsrpg.chitchat.Chitchat
version: ${project.version}
description: The simplest plugin for chitchat.
authors: [HmmmQuestionMark]
commands:
  ccreload:
    usage: /ccreload
  ccmute:
    usage: /ccmute <player>
    aliases: [ccm]
  ccunmute:
    usage: /ccunmute <player>
    aliases: [ccum]
  ccmsg:
    usage: /ccmsg <player> <message>
    aliases: [msg, pm]
  ccret:
    usage: /ccret <message>
    aliases: [ccr, ret, r]
permisions:
  chitchat.reload:
    default: op
  chitchat.mute:
    default: op
  chitchat.unmute:
    default: op
  chitchat.color:
    default: false
  chitchat.msg:
    default: true